from pathlib import Path

from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url

from app.core.config import settings
from app.db import engine


BASE_DIR = Path(__file__).resolve().parents[2]
SEED_SQL_PATH = BASE_DIR / "database" / "seed_admin_coworking.sql"


SCHEMA_SQL = """
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE TYPE tipo_sala AS ENUM (
  '1 Mesa de Trabalho',
  '2 Sala Individual',
  '3 Sala de Atendimento',
  '4 Sala de Reunião'
);

CREATE TYPE status_reserva AS ENUM (
  'Finalizada',
  'Em Andamento',
  'Cancelada',
  'Confirmada'
);

CREATE TYPE status_assinatura AS ENUM (
  'Ativa',
  'Cancelada',
  'Vencida'
);

CREATE TYPE tipo_notificacao AS ENUM (
  'Confirmação de Reserva',
  'Lembrete',
  'Alerta',
  'Renovação de Plano'
);

CREATE TABLE cliente (
  id_cliente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  cpf varchar NOT NULL UNIQUE,
  email varchar NOT NULL UNIQUE,
  telefone varchar NULL,
  senha varchar NOT NULL
);

CREATE TABLE usuario_cliente (
  id_cliente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  cpf char(11) NOT NULL UNIQUE,
  email varchar NOT NULL UNIQUE,
  telefone varchar NULL,
  senha varchar NOT NULL,
  CONSTRAINT chk_cpf_numerico CHECK (cpf ~ '^[0-9]{11}$')
);

CREATE TABLE sala (
  id_sala integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  capacidade integer NOT NULL,
  tipo tipo_sala NOT NULL,
  descricao text NULL,
  recursos text NULL,
  criado_em date NOT NULL,
  ativa boolean NOT NULL DEFAULT true
);

CREATE TABLE salas (
  id_sala integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  capacidade integer NOT NULL,
  tipo tipo_sala NOT NULL,
  descricao text NULL,
  recursos text NULL,
  criado_em date NOT NULL,
  CONSTRAINT chk_capacidade_pos CHECK (capacidade > 0)
);

CREATE TABLE planos (
  id_plano integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  acesso tipo_sala NOT NULL,
  preco numeric NOT NULL
);

CREATE TABLE reservas (
  id_reserva integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente integer NULL REFERENCES cliente(id_cliente) ON DELETE SET NULL,
  id_sala integer NULL REFERENCES sala(id_sala) ON DELETE RESTRICT,
  status status_reserva NOT NULL DEFAULT 'Confirmada',
  feito_em date NOT NULL,
  entrada timestamp without time zone NOT NULL,
  saida timestamp without time zone NOT NULL
);

CREATE TABLE assinaturas (
  id_assinatura integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente integer NULL REFERENCES cliente(id_cliente) ON DELETE SET NULL,
  id_plano integer NULL REFERENCES planos(id_plano) ON DELETE RESTRICT,
  status status_assinatura NOT NULL DEFAULT 'Ativa',
  validade date NOT NULL,
  feita_em date NOT NULL
);

CREATE TABLE avaliacao (
  id_avaliacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_reserva integer NULL REFERENCES reservas(id_reserva),
  nota integer NOT NULL,
  corpo varchar(255) NULL,
  criado_em date NOT NULL,
  CONSTRAINT ck_avaliacao_nota CHECK (nota >= 0 AND nota <= 5)
);

CREATE TABLE avaliacoes (
  id_avaliacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente integer NOT NULL REFERENCES usuario_cliente(id_cliente),
  id_sala integer NOT NULL REFERENCES salas(id_sala),
  id_reserva integer NOT NULL REFERENCES reservas(id_reserva),
  nota integer NOT NULL,
  corpo varchar(255) NULL,
  criado_em date NOT NULL,
  CONSTRAINT chk_nota_range CHECK (nota >= 0 AND nota <= 5),
  CONSTRAINT uq_avaliacao_reserva UNIQUE (id_reserva)
);

CREATE TABLE notificacao (
  id_notificacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_assinatura integer NULL REFERENCES assinaturas(id_assinatura) ON DELETE SET NULL,
  id_reserva integer NULL REFERENCES reservas(id_reserva) ON DELETE SET NULL,
  corpo text NOT NULL,
  tipo tipo_notificacao NOT NULL,
  lida boolean NOT NULL DEFAULT false,
  criado_em date NOT NULL
);

CREATE TABLE notificacoes (
  id_notificacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente integer NOT NULL REFERENCES usuario_cliente(id_cliente),
  corpo text NOT NULL,
  tipo tipo_notificacao NOT NULL,
  lida boolean NOT NULL DEFAULT false,
  criado_em date NOT NULL
);
"""


def _quote_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def _create_database_if_missing() -> str:
    target_url = make_url(settings.database_url)
    database_name = target_url.database

    if not database_name:
        raise RuntimeError("DATABASE_URL sem nome de banco de dados.")

    maintenance_url = target_url.set(database="postgres")
    maintenance_engine = create_engine(maintenance_url, isolation_level="AUTOCOMMIT", future=True)

    try:
        with maintenance_engine.connect() as connection:
            exists = connection.scalar(
                text("SELECT 1 FROM pg_database WHERE datname = :database_name"),
                {"database_name": database_name},
            )
            if exists is None:
                connection.execute(text(f"CREATE DATABASE {_quote_identifier(database_name)}"))
    finally:
        maintenance_engine.dispose()

    return database_name


def bootstrap_database() -> dict[str, int | str]:
    if not SEED_SQL_PATH.exists():
        raise RuntimeError(f"Arquivo de seed nao encontrado: {SEED_SQL_PATH}")

    database_name = _create_database_if_missing()
    seed_sql = (
        SEED_SQL_PATH.read_text(encoding="utf-8")
        .replace("\nBEGIN;\n", "\n")
        .replace("\nCOMMIT;", "")
    )
    target_engine = create_engine(settings.database_url, future=True)

    try:
        with target_engine.begin() as connection:
            connection.exec_driver_sql(SCHEMA_SQL)
            connection.exec_driver_sql(seed_sql)
    finally:
        target_engine.dispose()
        engine.dispose()

    return {
        "database": database_name,
        "clientes": 8,
        "salas": 7,
        "planos": 4,
        "assinaturas": 8,
        "reservas": 12,
        "avaliacoes": 5,
        "notificacoes": 5,
    }
