from __future__ import annotations

import base64
import hashlib
import os
from decimal import Decimal

import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT


HOST = os.environ["PGHOST"]
PORT = int(os.environ.get("PGPORT", "5432"))
USER = os.environ["PGUSER"]
PASSWORD = os.environ["PGPASSWORD"]
DB_NAME = os.environ.get("PGDATABASE", "apiEixo6")


SCHEMA_SQL = """
DO $$
BEGIN
    CREATE TYPE tipo_sala AS ENUM (
        '1 Mesa de Trabalho',
        '2 Sala Individual',
        '3 Sala de Atendimento',
        '4 Sala de Reunião'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE status_reserva AS ENUM (
        'Finalizada',
        'Em Andamento',
        'Cancelada',
        'Confirmada'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE status_assinatura AS ENUM (
        'Ativa',
        'Cancelada',
        'Vencida'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    CREATE TYPE tipo_notificacao AS ENUM (
        'Confirmação de Reserva',
        'Lembrete',
        'Alerta',
        'Renovação de Plano'
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS cliente (
    id_cliente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(50) NOT NULL,
    cpf varchar(11) NOT NULL UNIQUE,
    email varchar(100) NOT NULL UNIQUE,
    telefone varchar(11),
    senha varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS sala (
    id_sala integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(50) NOT NULL,
    capacidade integer NOT NULL CHECK (capacidade > 0),
    tipo tipo_sala NOT NULL,
    descricao text,
    recursos text,
    criado_em date NOT NULL DEFAULT CURRENT_DATE,
    ativa boolean NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS planos (
    id_plano integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(50) NOT NULL,
    acesso tipo_sala NOT NULL,
    preco numeric(10, 2) NOT NULL CHECK (preco >= 0)
);

CREATE TABLE IF NOT EXISTS reservas (
    id_reserva integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente integer REFERENCES cliente(id_cliente) ON DELETE SET NULL,
    id_sala integer REFERENCES sala(id_sala) ON DELETE RESTRICT,
    status status_reserva NOT NULL DEFAULT 'Confirmada',
    feito_em date NOT NULL DEFAULT CURRENT_DATE,
    entrada timestamp without time zone NOT NULL,
    saida timestamp without time zone NOT NULL,
    CONSTRAINT ck_reservas_intervalo CHECK (entrada < saida)
);

CREATE TABLE IF NOT EXISTS avaliacao (
    id_avaliacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva integer REFERENCES reservas(id_reserva),
    nota integer NOT NULL,
    corpo varchar(255),
    criado_em date NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT ck_avaliacao_nota CHECK (nota >= 0 AND nota <= 5)
);

CREATE TABLE IF NOT EXISTS assinaturas (
    id_assinatura integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente integer REFERENCES cliente(id_cliente) ON DELETE SET NULL,
    id_plano integer REFERENCES planos(id_plano) ON DELETE RESTRICT,
    status status_assinatura NOT NULL DEFAULT 'Ativa',
    validade date NOT NULL,
    feita_em date NOT NULL DEFAULT CURRENT_DATE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_assinaturas_cliente_ativa
ON assinaturas(id_cliente)
WHERE status = 'Ativa';

CREATE TABLE IF NOT EXISTS notificacao (
    id_notificacao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_assinatura integer REFERENCES assinaturas(id_assinatura) ON DELETE SET NULL,
    id_reserva integer REFERENCES reservas(id_reserva) ON DELETE SET NULL,
    corpo text NOT NULL,
    tipo tipo_notificacao NOT NULL,
    lida boolean NOT NULL DEFAULT FALSE,
    criado_em date NOT NULL DEFAULT CURRENT_DATE
);
"""


def hash_senha(value: str) -> str:
    digest = hashlib.sha256(value.encode("utf-8")).digest()
    token = base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")
    return f"sha256${token}"


def connect(database: str):
    return psycopg2.connect(
        host=HOST,
        port=PORT,
        user=USER,
        password=PASSWORD,
        dbname=database,
        connect_timeout=12,
    )


def ensure_database() -> None:
    conn = connect("postgres")
    conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (DB_NAME,))
            if cur.fetchone() is None:
                cur.execute(f'CREATE DATABASE "{DB_NAME}"')
    finally:
        conn.close()


def seed_data() -> None:
    senha = hash_senha("123456")
    with connect(DB_NAME) as conn:
        with conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)

            clientes = [
                ("Ana Souza", "11122233344", "ana.souza@example.com", "11911112222", senha),
                ("Bruno Lima", "22233344455", "bruno.lima@example.com", "11922223333", senha),
                ("Carla Mendes", "33344455566", "carla.mendes@example.com", "11933334444", senha),
                ("Diego Rocha", "44455566677", "diego.rocha@example.com", "11944445555", senha),
            ]
            cur.executemany(
                """
                INSERT INTO cliente (nome, cpf, email, telefone, senha)
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (cpf) DO UPDATE SET
                    nome = EXCLUDED.nome,
                    email = EXCLUDED.email,
                    telefone = EXCLUDED.telefone
                """,
                clientes,
            )

            salas = [
                ("Mesa Flex 01", 1, "1 Mesa de Trabalho", "Mesa em área compartilhada", "Wi-Fi, tomada, café", True),
                ("Sala Individual Norte", 1, "2 Sala Individual", "Sala privativa para foco", "Wi-Fi, monitor, armário", True),
                ("Atendimento Azul", 3, "3 Sala de Atendimento", "Sala para atendimento reservado", "Wi-Fi, mesa redonda", True),
                ("Reunião Aurora", 8, "4 Sala de Reunião", "Sala ampla para reuniões", "TV, quadro branco, videoconferência", True),
            ]
            cur.executemany(
                """
                INSERT INTO sala (nome, capacidade, tipo, descricao, recursos, ativa)
                SELECT %s, %s, %s::tipo_sala, %s, %s, %s
                WHERE NOT EXISTS (SELECT 1 FROM sala WHERE nome = %s)
                """,
                [(nome, capacidade, tipo, descricao, recursos, ativa, nome) for nome, capacidade, tipo, descricao, recursos, ativa in salas],
            )

            planos = [
                ("Básico", "1 Mesa de Trabalho", Decimal("149.90")),
                ("Profissional", "2 Sala Individual", Decimal("349.90")),
                ("Atendimento", "3 Sala de Atendimento", Decimal("499.90")),
                ("Empresarial", "4 Sala de Reunião", Decimal("799.90")),
            ]
            cur.executemany(
                """
                INSERT INTO planos (nome, acesso, preco)
                SELECT %s, %s::tipo_sala, %s
                WHERE NOT EXISTS (SELECT 1 FROM planos WHERE nome = %s)
                """,
                [(nome, acesso, preco, nome) for nome, acesso, preco in planos],
            )

            cur.execute(
                """
                INSERT INTO assinaturas (id_cliente, id_plano, status, validade, feita_em)
                SELECT c.id_cliente, p.id_plano, 'Ativa'::status_assinatura, CURRENT_DATE + INTERVAL '30 days', CURRENT_DATE
                FROM cliente c
                JOIN planos p ON p.nome = 'Profissional'
                WHERE c.cpf = '11122233344'
                ON CONFLICT DO NOTHING
                """
            )
            cur.execute(
                """
                INSERT INTO assinaturas (id_cliente, id_plano, status, validade, feita_em)
                SELECT c.id_cliente, p.id_plano, 'Ativa'::status_assinatura, CURRENT_DATE + INTERVAL '30 days', CURRENT_DATE
                FROM cliente c
                JOIN planos p ON p.nome = 'Básico'
                WHERE c.cpf = '22233344455'
                ON CONFLICT DO NOTHING
                """
            )

            cur.execute(
                """
                INSERT INTO reservas (id_cliente, id_sala, status, feito_em, entrada, saida)
                SELECT c.id_cliente, s.id_sala, 'Confirmada'::status_reserva, CURRENT_DATE,
                       date_trunc('hour', now()) + INTERVAL '1 day 10 hours',
                       date_trunc('hour', now()) + INTERVAL '1 day 12 hours'
                FROM cliente c, sala s
                WHERE c.cpf = '11122233344' AND s.nome = 'Reunião Aurora'
                  AND NOT EXISTS (
                      SELECT 1 FROM reservas rx
                      WHERE rx.id_cliente = c.id_cliente
                        AND rx.id_sala = s.id_sala
                        AND rx.entrada = date_trunc('hour', now()) + INTERVAL '1 day 10 hours'
                  )
                """
            )
            cur.execute(
                """
                INSERT INTO reservas (id_cliente, id_sala, status, feito_em, entrada, saida)
                SELECT c.id_cliente, s.id_sala, 'Confirmada'::status_reserva, CURRENT_DATE,
                       date_trunc('hour', now()) + INTERVAL '2 days 14 hours',
                       date_trunc('hour', now()) + INTERVAL '2 days 15 hours'
                FROM cliente c, sala s
                WHERE c.cpf = '22233344455' AND s.nome = 'Sala Individual Norte'
                  AND NOT EXISTS (
                      SELECT 1 FROM reservas rx
                      WHERE rx.id_cliente = c.id_cliente
                        AND rx.id_sala = s.id_sala
                        AND rx.entrada = date_trunc('hour', now()) + INTERVAL '2 days 14 hours'
                  )
                """
            )
            cur.execute(
                """
                INSERT INTO reservas (id_cliente, id_sala, status, feito_em, entrada, saida)
                SELECT c.id_cliente, s.id_sala, 'Finalizada'::status_reserva, CURRENT_DATE - INTERVAL '2 days',
                       date_trunc('hour', now()) - INTERVAL '2 days 10 hours',
                       date_trunc('hour', now()) - INTERVAL '2 days 9 hours'
                FROM cliente c, sala s
                WHERE c.cpf = '33344455566' AND s.nome = 'Atendimento Azul'
                  AND NOT EXISTS (
                      SELECT 1 FROM reservas rx
                      WHERE rx.id_cliente = c.id_cliente
                        AND rx.id_sala = s.id_sala
                        AND rx.entrada = date_trunc('hour', now()) - INTERVAL '2 days 10 hours'
                  )
                """
            )

            cur.execute(
                """
                INSERT INTO avaliacao (id_reserva, nota, corpo, criado_em)
                SELECT r.id_reserva, 5, 'Sala limpa, confortável e bem equipada.', CURRENT_DATE
                FROM reservas r
                JOIN cliente c ON c.id_cliente = r.id_cliente
                WHERE c.cpf = '11122233344'
                  AND NOT EXISTS (SELECT 1 FROM avaliacao a WHERE a.id_reserva = r.id_reserva)
                ORDER BY r.id_reserva
                LIMIT 1
                """
            )

            cur.execute(
                """
                INSERT INTO notificacao (id_assinatura, id_reserva, corpo, tipo, lida, criado_em)
                SELECT a.id_assinatura, r.id_reserva, 'Sua reserva foi confirmada com sucesso.',
                       'Confirmação de Reserva'::tipo_notificacao, false, CURRENT_DATE
                FROM assinaturas a
                JOIN reservas r ON r.id_cliente = a.id_cliente
                JOIN cliente c ON c.id_cliente = a.id_cliente
                WHERE c.cpf = '11122233344'
                  AND NOT EXISTS (
                      SELECT 1 FROM notificacao n
                      WHERE n.id_assinatura = a.id_assinatura
                        AND n.id_reserva = r.id_reserva
                        AND n.tipo = 'Confirmação de Reserva'
                  )
                ORDER BY a.id_assinatura, r.id_reserva
                LIMIT 1
                """
            )
            cur.execute(
                """
                INSERT INTO notificacao (id_assinatura, corpo, tipo, lida, criado_em)
                SELECT a.id_assinatura, 'Sua assinatura vence em breve.',
                       'Renovação de Plano'::tipo_notificacao, false, CURRENT_DATE
                FROM assinaturas a
                JOIN cliente c ON c.id_cliente = a.id_cliente
                WHERE c.cpf = '22233344455'
                  AND NOT EXISTS (
                      SELECT 1 FROM notificacao n
                      WHERE n.id_assinatura = a.id_assinatura
                        AND n.tipo = 'Renovação de Plano'
                  )
                ORDER BY a.id_assinatura
                LIMIT 1
                """
            )

        conn.commit()


def print_counts() -> None:
    with connect(DB_NAME) as conn:
        with conn.cursor() as cur:
            for table in ("cliente", "sala", "planos", "assinaturas", "reservas", "avaliacao", "notificacao"):
                cur.execute(f"SELECT COUNT(*) FROM {table}")
                print(f"{table}: {cur.fetchone()[0]}")


if __name__ == "__main__":
    ensure_database()
    seed_data()
    print_counts()
