@AvaliacaoApi_HostAddress = http://localhost:5158

GET {{AvaliacaoApi_HostAddress}}/api/avaliacao
Accept: application/json

###

GET {{AvaliacaoApi_HostAddress}}/api/avaliacao/1
Accept: application/json

###

POST {{AvaliacaoApi_HostAddress}}/api/avaliacao
Content-Type: application/json

{
  "idReserva": 1,
  "nota": 9,
  "corpo": "Ambiente muito bom e organizado.",
  "criadoEm": "2026-04-09"
}

###

PUT {{AvaliacaoApi_HostAddress}}/api/avaliacao/1
Content-Type: application/json

{
  "idReserva": 1,
  "nota": 10,
  "corpo": "Atendimento excelente.",
  "criadoEm": "2026-04-09"
}

###

DELETE {{AvaliacaoApi_HostAddress}}/api/avaliacao/1
